package graphics;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.util.ArrayList;

import javax.swing.AbstractAction;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.Timer;

import sensors.KeyboardSensor;
import sdlNetwork.*;

public class Graphics extends JPanel{
	JFrame frame;
	ArrayList<KeyboardSensor> keySensors;
	private State currentState = new State("Temp");
	
	public Graphics(){
		this(new ArrayList<KeyboardSensor>());
	}
	
	public Graphics(ArrayList<KeyboardSensor> keySensors){
		this.keySensors = keySensors;
		frame = new JFrame("Test");
		init();
		for(KeyboardSensor s : keySensors){
			frame.addKeyListener(s);
		}
	}
	
	private void init() {
		frame.setMinimumSize(new Dimension(480, 480));
		frame.setSize(600, 600);
		frame.add(this);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setVisible(true);
		frame.setFocusable(true);
		this.setFocusable(true);
		Timer timer = new Timer(36, new TimeAction());
		timer.start();
	}
	
	public void addKeyboardSensor(KeyboardSensor keySensor){
		keySensors.add(keySensor);
		frame.addKeyListener(keySensor);
	}
	
	public void setState(State s) {
		currentState = s;
	}
	
	public void paintComponent(java.awt.Graphics g) {
		paintState((Graphics2D) g);
		paintKeys((Graphics2D) g);
	}
	
	public void paintState(Graphics2D g2) {
		g2.drawString("Current State = " + currentState.toString(), 300, 0);
	}
	
	public void paintKeys(Graphics2D g2) {
		for (KeyboardSensor ks : keySensors) {
			int ydisplace = 20;
			g2.drawString("Key", 0, 0);
			g2.drawString("Signal", 50, 0);
			g2.drawString(String.valueOf((char) ks.getKey()), 0, ydisplace);
			g2.drawString(ks.getSignal().toString(), 50, ydisplace);
			ydisplace += 20;
		}
	}
	
	class TimeAction extends AbstractAction {

		/**
		 * Moves the ball and paddle(s) when called by the timer.
		 * 
		 * @param arg0
		 *            Event generated by the timer
		 */
		public void actionPerformed(ActionEvent arg0) {
			Graphics.this.repaint();
		}
	}
}
