package graphics;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.util.ArrayList;

import javax.swing.AbstractAction;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.Timer;

import sensors.KeyboardSensor;
import sdlNetwork.*;

public class Graphics extends JPanel{
	JFrame frame;
	ArrayList<KeyboardSensor> keySensors;
	private State currentState = new State("Temp");
	
	public Graphics(){
		this(new ArrayList<KeyboardSensor>());
	}
	
	public Graphics(ArrayList<KeyboardSensor> keySensors){
		this.keySensors = keySensors;
		frame = new JFrame("Test");
		init();
		this.setBackground(Color.WHITE);
		for(KeyboardSensor s : keySensors){
			frame.addKeyListener(s);
		}
	}
	
	private void init() {
		frame.setMinimumSize(new Dimension(480, 480));
		frame.setSize(700, 700);
		frame.add(this);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setVisible(true);
		frame.setFocusable(true);
		frame.setBackground(Color.WHITE);
		this.setFocusable(true);
		Timer timer = new Timer(36, new TimeAction());
		timer.start();
	}
	
	public void addKeyboardSensor(KeyboardSensor keySensor){
		keySensors.add(keySensor);
		frame.addKeyListener(keySensor);
	}
	
	public void setState(State s) {
		currentState = s;
	}
	
	public void paintComponent(java.awt.Graphics g) {
		super.paintComponent(g);
		paintState((Graphics2D) g);
		paintKeys((Graphics2D) g);
	}
	
	public void paintState(Graphics2D g2) {
		int x = 300;
		int yTop = 25;
		int ydisplace = yTop + 25; //sets initial value of displacement between state and connections
		
		//paints state
		g2.drawString("Current State = " + currentState.toString(), x, yTop);
		
		//paints connections
		g2.drawString("Connections (StartState ~ Signal ~ Actions ~ EndState)", x, ydisplace);
		ydisplace += 25; //displacement between label and actual connections
		for (Connection s : currentState.getConnections()) {
			g2.drawString(s.toString(), x, ydisplace);
			ydisplace += 20; //the displacement between lines
		}
	}
	
	public void paintKeys(Graphics2D g2) {
		int yTop = 25;
		int ydisplace = yTop + 25; //sets initial value of displacement between label and signals
		int xKey = 0;
		int xSignal = 75;
		for (KeyboardSensor ks : keySensors) {
			g2.drawString("Key", xKey, yTop);
			g2.drawString("Signal", xSignal, yTop);
			g2.drawString(String.valueOf((char) ks.getKey()), xKey, ydisplace);
			g2.drawString(ks.getSignal().toString(), xSignal, ydisplace);
			ydisplace += 20; //the displacement between lines
		}
	}
	
	class TimeAction extends AbstractAction {

		/**
		 * Moves the ball and paddle(s) when called by the timer.
		 * 
		 * @param arg0
		 *            Event generated by the timer
		 */
		public void actionPerformed(ActionEvent arg0) {
			Graphics.this.repaint();
		}
	}
}
